[package]
name = "andromeda-modules"
version = "0.1.0"
authors = ["Connor Barr <crnbarr@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cosmwasm-std = "0.16.0"
cw-storage-plus = "0.8.0"
serde = { version = "1.0.127", default-features = false, features = ["derive"] }
schemars = "0.8.1"
itertools = "0.10.0"
cw721 = "0.8.0"
