[package]
name = "andromeda-modules"
version = "0.1.0"
authors = ["Connor Barr <crnbarr@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cosmwasm-std = { version = "0.10.1" }
cosmwasm-storage = { version = "0.10.1" }
serde = { version = "1.0.103", default-features = false, features = ["derive"] }
schemars = "0.7"
itertools = "0.10.0"