[package]
name = "andromeda-modules"
version = "0.1.0"
authors = ["Connor Barr <crnbarr@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cosmwasm-std = { version = "0.15.2" }
cosmwasm-storage = { version = "0.15.2" }
cw-storage-plus = "0.7.0"
serde = { version = "1.0.103", default-features = false, features = ["derive"] }
schemars = "0.8.3"
itertools = "0.10.0"